### ISSUE TITLE
create CONTRIBUTING.md

### ISSUE THREAD

**Issue by emdupre** [emdupre/me-ica#6]
Create contributing guidelines to make it easier for others to onboard to the project. See @KirstieJane for a good [example](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/CODE_OF_CONDUCT.md)

**Comment by emdupre** [comment]
[Done](https://github.com/emdupre/me-ica/blob/py3/CONTRIBUTING.md) ! 🎉

**Comment by KirstieJane** [comment]
YEAAAH! Way to go! ✨ 🙌 🎈
